---
# WebGIS information
portal_url: https://gis.somemunicipality.com/portal
username: SomeUser
password: SomePassword
# If the profile field is used - portal_url, username, and passwords fields are ignored
profile: Profile_SomeGIS
feat_id:
feat_lyr_num:
rec_id:
rec_tbl_num:
# Specify geodatabase version or leave blank to use DEFAULT version
gdb_version:

# Feature to record field Mapping
f_fields:
  f1: field1
  f2: field2
  f3: field3
  f4: field4
  date: date_field
  key: GlobalID

r_fields:
  f1: field1
  f2: field2
  f3: field3
  f4: field4
  date: date_field
  key: ParentID
...
