---
### WebGIS information ###
portal_url: https://gis.examplemunicipality.com/portal
username: ExampleUser
password: ExamplePassword
# If the profile field is used - portal_url, username, and passwords fields are ignored
profile: ExampleProfile
feat_id:
feat_lyr_num:
rec_id:
rec_tbl_num:
# Specify geodatabase version or leave blank to use DEFAULT version
gdb_version:

### Number of days to look back at records ###
lookback: 30

### Feature-to-Record field Mapping ###
# Feature fields
f_fields:
  f1: field1
  f2: field2
  f3: field3
  f4: field4
  f5: field5
  f6: field6
  f7: field7
  f8: field8
  date: date_field
  key: GlobalID
# Record fields
r_fields:
  f1: field1
  f2: field2
  f3: field3
  f4: field4
  f5: field5
  f6: field6
  f7: field7
  f8: field8
  date: date_field
  key: ParentID
...
